### ISSUE TITLE
Can't open Zarr files with labels

### ISSUE THREAD

**Issue by FIrgolitsch** [ome/napari-ome-zarr#104]
Hello,

When I try to open an OME-Zarr file with labels inside the file I get an unspecified error and the files fails to load. This happens with the newest version 0.4.19 with the newest version of the plugin. I do not have this issue on older versions (0.4.18) with possibly an older version of the plugin. I think it might be related to the issue I posted here: https://github.com/ome/ome-zarr-py/issues/357

**Comment by psobolewskiPhD** [comment]
With napari 0.4.19, ome-zarr 0.8.3 and  0.5.2 of this plugin I can load this ome zarr with labels:
https://ome.github.io/ome-ngff-validator/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0001A/2551.zarr/A/1/0/
`napari https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0001A/2551.zarr/A/1/0`

**Comment by FIrgolitsch** [comment]
Forgot this issue existed. Yeah, with version 0.8.3 this problem was fixed! It was due to some dependency of ome-zarr 0.8.2 that was misbehaving.
