### ISSUE TITLE
Tests fail with ome-zarr 0.8.3

### ISSUE THREAD

**Issue by dstansby** [ome/napari-ome-zarr#108]
In https://github.com/ome/napari-ome-zarr/pull/107 I had to pin the version of `ome-zarr` to get the tests to pass; this should be fixed so `napari-ome-zarr` works with the latest version of `ome-zarr`.  A quick glance at [the diff between version 0.8.2 and 0.8.3 ](https://github.com/ome/ome-zarr-py/compare/v0.8.2...v0.8.3)doesn't reveal anything obvious to me that would have broke the tests here...

**Comment by dstansby** [comment]
At a guess, [ome/ome-zarr-py@`c159b79` (#322)](https://github.com/ome/ome-zarr-py/pull/322/commits/c159b794bef640046d5a40bb4096c39af63d24fd) might be the culprit?

**Comment by psobolewskiPhD** [comment]
Interesting, I can use the plugin ok with ome-zarr 0.8.3, with napari 0.4.19.
e.g. `napari https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0001A/2551.zarr/A/1/0`
Here's the validation:
https://ome.github.io/ome-ngff-validator/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0001A/2551.zarr/A/1/0/

**Comment by psobolewskiPhD** [comment]
No, just reading.
