### ISSUE TITLE
Compatibility with latest ome-zarr-py

### ISSUE THREAD

**Issue by ziw-liu** [ome/napari-ome-zarr#111]
The latest version (released July 2022), is no longer compatible with the latest ome-zarr-py. Namely, upgrading from ome-zarr==0.8.3 to ome-zarr==0.9.0 results in empty layer names.

<img width="380" alt="image" src="https://github.com/ome/napari-ome-zarr/assets/67518483/369e9ee7-d8c4-43d8-b10a-392a75867a92">

To reproduce, make a new virtual environment, install:

```sh
pip install napari pyqt5 napari-ome-zarr
```

And open a zarr store with different channel names.

**Comment by psobolewskiPhD** [comment]
This appears to be resolved with 0.9.0

**Comment by ziw-liu** [comment]
napari-ome-zarr 0.6.1 is now compatible with ome-zarr 0.9.0.
