### ISSUE TITLE
Labels should be opened as label layer

### ISSUE THREAD

**Issue by constantinpape** [ome/napari-ome-zarr#35]
After fixing the issues with my data observed in #33. The labels are now loaded by the plugin.
However they are loaded as image layer:
![image](https://user-images.githubusercontent.com/4263537/158467503-e73a7f83-1ad5-490d-9f67-4d82dd9fb224.png)

It would make more sense to load them as label layer instead. Note that this is particularly annoying right now since it's not possible to convert them into a label layer due to #34.

**Comment by will-moore** [comment]
Can you try `napari https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.3/idr0079A/9836998.zarr`, which is an example with labels that show up as labels for me.
Can you share the data you're viewing above?

**Comment by constantinpape** [comment]
> Can you try `napari https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.3/idr0079A/9836998.zarr`, which is an example with labels that show up as labels for me.

Yes, that opens it as labels layer for me too.

> Can you share the data you're viewing above?

I uploaded the data here: https://oc.embl.de/index.php/s/wfpdHpgHseGUTYK. It is from the example here: https://github.com/ome/ome-ngff-prototypes/tree/main/workflows/spatial-transcriptomics-example

**Comment by constantinpape** [comment]
Yes, this fixes the issue.
