### ISSUE TITLE
Layer names

### ISSUE THREAD

**Issue by constantinpape** [ome/napari-ome-zarr#36]
Currently, the filename is used to determine the layer names:
![image](https://user-images.githubusercontent.com/4263537/158536199-c07f9994-6105-41c5-ab39-ae057615c9c2.png)
I think it would be better to use the "name" field from the multiscale spec instead (if it's given).
This would make the layers easier to distinguish.

**Comment by constantinpape** [comment]
Fyi, I noticed that this works for some other ome.zarr files, i.e. the `name` field is used for the layers. 
However, it does not wok for this data https://oc.embl.de/index.php/s/wfpdHpgHseGUTYK, which has a few other issues as well (#37, #35).
It would be important to understand if this is a problem with the data (which is produced with [this script](https://github.com/ome/ome-ngff-prototypes/tree/main/workflows/spatial-transcriptomics-example) using `ome-zarr-py`) or the napari plugin (or both :D)

**Comment by constantinpape** [comment]
After fixing the issue with the `image-label` field this looks a bit different now:
![image](https://user-images.githubusercontent.com/4263537/158897892-e7b081e1-01a4-4f2c-9258-c9f0fdf5838c.png)
It uses the filename for the image data and the `name` field for the label data. I think that it should use the `name` field for all of the layers (if it is given, which is the case here; it's `image` for the image data)

**Comment by constantinpape** [comment]
This issue is still there. Here's the latest version of the file: https://oc.embl.de/index.php/s/yfwGLkFRHsopcug
Created with https://github.com/ome/ome-ngff-prototypes/tree/main/workflows/spatial-transcriptomics-example

**Comment by will-moore** [comment]
Should be fixed by https://github.com/ome/ome-zarr-py/pull/214
