### ISSUE TITLE
napari reader preferences are not respected

### ISSUE THREAD

**Issue by maweigert** [ome/napari-ome-zarr#41]
Hi, 

When drag/drop a zarr folder into napari while multiple plugins capable of reading zarr exists, the napari reader preference dialog is currently always displayed, without the option of saving the choice as part of the preferences (which is expected behavior). 

I guess that might be due to a `napari.manifest` missing that would register a filename pattern, so simply adding this might already solve the issue.

Cheers,
M

PS: thanks a lot for the plugin, it's very useful!

**Comment by joshmoore** [comment]
Hey @maweigert. Thanks for the heads up! I assume this is equivalent to #27 (cc: @DragaDoncila) though now there are tools!

**Comment by maweigert** [comment]
Yep, `napari.manifest`should register the reader (and filter for file extension, although I don't know whether that currently works for *directory* names as well)

**Comment by will-moore** [comment]
With https://github.com/ome/napari-ome-zarr/blob/main/napari_ome_zarr/napari.yaml using latest (not released yet) this seems to be working for me now:

Drag a folder onto napari for the first time:

<img width="471" alt="Screenshot 2022-07-22 at 14 35 01" src="https://user-images.githubusercontent.com/900055/180450857-c78de978-5532-4e22-a411-42d5b2247c91.png">

After that, I can drag other `path/to/image.zarr/` folders onto napari and they open without showing the dialog again.
