### ISSUE TITLE
open ngff file with lower resolution pyramid

### ISSUE THREAD

**Issue by satra** [ome/napari-ome-zarr#49]
i'm trying the viewer on this file to see if it will do zoom based resolution fetch, but it opens at the highest resolution.

`napari --plugin napari-ome-zarr 'https://dandiarchive.s3.amazonaws.com/zarr/7723d02f-1f71-4553-a7b0-47bda1ae8b42/'`

i'm on a 16" macbook pro. wondering if it's because of the resolution of display, and if there is a way to force it to a different pyramid level by default.

**Comment by joshmoore** [comment]
Hey @satra. Good question! Unless something has changed (and that's certainly possible; napari goes fast) the plugin interface implemented here doesn't allow us to specify.

@jni, @sofroniewn, @tlambert03, @DragaDoncila, etc. might be able to tell us more.

**Comment by satra** [comment]
thanks @joshmoore  and @will-moore -  indeed these are at 128^3, which has it's challenges.  i was simply testing how much view-based rendering napari provides, and after it loaded i was able to squeeze the viewport to have it access a lower resolution pyramid. so indeed it is tied to rich pixel density of my display. perhaps that can be parameterized in a way to balance pyramid resolution and FOV.

i'll close this for now. feel free to re-open if it's useful for tracking a pending feature.

**Comment by jni** [comment]
FYI we are aware of these issues @satra, we intend to improve this by first loading the lowest resolution and then progressively refining it up to the resolution of the display. But it will take a while to get there. :pray:
