### ISSUE TITLE
Demo zarr does not work

### ISSUE THREAD

**Issue by maweigert** [ome/napari-ome-zarr#56]
Hi, 

It appears that in the current versions (`0.5.0` and `main`) the opening of the demo url does not work anymore:

`napari "https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.3/9836842.zarr/"`

yields 

`napari.errors.reader_errors.NoAvailableReaderError: No plugin found capable of reading https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.3/9836842.zarr/`

versions:
```
napari : 0.4.16
zarr : 2.11.3
napari_ome_zarr : 0.5.1.dev4+g4e506d
```

**Comment by sbesson** [comment]
Thanks @maweigert, we also noticed that the `napari-ome-zarr` plugin is currently broken with the latest and recent versions of `napari` - see https://github.com/ome/napari-ome-zarr/pull/55#issuecomment-1169828031. We are still unsure where this regression comes from

**Comment by sbesson** [comment]
Also tried to downgrade to former version of the plugin and/or napari but the plugin is still not registered by the plugin engine

```
(napari) sbesson@Sebastiens-MacBook-Pro ~ % napari --version
/Users/sbesson/miniconda3/envs/napari/lib/python3.10/site-packages/napari/__main__.py:423: UserWarning: pythonw executable not found.
To unfreeze the menubar on macOS, click away from napari to another app, then reactivate napari. To avoid this problem, please install python.app in conda using:
conda install -c conda-forge python.app
  warnings.warn(msg)
napari version 0.4.12
(napari) sbesson@Sebastiens-MacBook-Pro ~ % pip freeze | grep napari
napari @ file:///home/conda/feedstock_root/build_artifacts/napari_1634857948574/work
napari-console @ file:///home/conda/feedstock_root/build_artifacts/napari-console_1644771676323/work
napari-ome-zarr==0.4.0
napari-plugin-engine @ file:///home/conda/feedstock_root/build_artifacts/napari-plugin-engine_1637358573066/work
napari-svg @ file:///home/conda/feedstock_root/build_artifacts/napari-svg_1652348013801/work
(napari) sbesson@Sebastiens-MacBook-Pro ~ % napari --plugin-info    
/Users/sbesson/miniconda3/envs/napari/lib/python3.10/site-packages/napari/__main__.py:423: UserWarning: pythonw executable not found.
To unfreeze the menubar on macOS, click away from napari to another app, then reactivate napari. To avoid this problem, please install python.app in conda using:
conda install -c conda-forge python.app
  warnings.warn(msg)
PluginManager for "napari"
(12 hook specs and 4 plugins)
---------------------------------------------
builtins v0.4.12                                 6 hooks
  - napari_get_reader            
  - napari_get_writer            
  - napari_write_image           
  - napari_write_labels          
  - napari_write_points          
  - napari_write_shapes          

console v0.0.4                                   0 hooks

scikit-image v0.4.12                             1 hooks
  - napari_provide_sample_data   

svg v0.1.6                                       6 hooks
  - napari_get_writer            
  - napari_write_image           
  - napari_write_labels          
  - napari_write_points          
  - napari_write_shapes          
  - napari_write_vectors         


Blocked Plugins:
----------------
napari-svg
napari-ome-zarr
napari
(napari) sbesson@Sebastiens-MacBook-Pro ~ % cat napari.yml      
name: napari
channels:
  - conda-forge
  - defaults
dependencies:
  - "napari<0.4.13"
  - pip
  - pip:
    - "napari-ome-zarr<0.5"
```

**Comment by DragaDoncila** [comment]
Hi team, reproducing my response from [this comment here](https://github.com/ome/napari-ome-zarr/pull/55#issuecomment-1170592918) for visibility:

The URL does not open because it does not match the provided `filename_pattern` due to the trailing `/`. Essentially, running `napari "https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.3/9836842.zarr"` (note no trailing slash) works as expected. To remedy this, you could update your example to remove the trailing slash, or update your `napari.yaml` to add a dedicated pattern for remote URLs e.g.

```yaml
name: napari-ome-zarr
schema_version: 0.1.0
contributions:
  commands:
    - id: napari-ome-zarr.get_reader
      title: Get Reader
      python_name: napari_ome_zarr._reader:napari_get_reader
  readers:
    - command: napari-ome-zarr.get_reader
      filename_patterns:
        - "*.zarr"
        - "https://*.zarr/" 
      accepts_directories: true

```

**Comment by sbesson** [comment]
@maweigert can you confirm removing the trailing slash fixes your issue? #55 should also add support for URIs with trailing slash in the upcoming release of the `napari-ome-zarr` plugin

**Comment by maweigert** [comment]
Hi All,

thanks for looking into this! 

> @maweigert can you confirm removing the trailing slash fixes your issue

Yes, that was it! it does work without the trailing slash. Thanks!

**Comment by maweigert** [comment]
Additionally, when using the branch in PR #55 it does work again with the trailing slash. As I assume this will be merged, I am closing now :)

**Comment by joshmoore** [comment]
Thanks for the feedback, @maweigert!
